steps:
- id: 'Build image'
  name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '--tag=us-east4-docker.pkg.dev/prj-hml-excelencia/coletor/coletor-fe:$SHORT_SHA', '--tag=us-east4-docker.pkg.dev/prj-hml-excelencia/coletor/coletor-fe:latest','-f', './.devops/Dockerfile.prod', '.' ]

- id: 'Push image'
  name: 'gcr.io/cloud-builders/docker'
  args: [ 'push', 'us-east4-docker.pkg.dev/prj-hml-excelencia/coletor/coletor-fe:$SHORT_SHA']

- id: Configure kubectl
  name: gcr.io/cloud-builders/kubectl
  args:
    - cluster-info
  env:
    - PROJECT=prj-hml-excelencia
    - KUBECONFIG=/workspace/.kube/config     
    - CLOUDSDK_COMPUTE_REGION=us-east4
    - CLOUDSDK_COMPUTE_ZONE=us-east4
    - CLOUDSDK_CONTAINER_CLUSTER=gf-gcloud-hml

- id: Deploy K8s
  name: 'gcr.io/prj-hml-excelencia/helm'
  args:
    - 'upgrade'
    - '--install'
    - 'coletor-fe'
    - './.devops/coletor-fe'
    - '--set=image.tag=$SHORT_SHA'
    - '--namespace=coletor'
    - '--wait'
  env:
    - HELM_HOME=/workspace
    - KUBECONFIG=/workspace/.kube/config
    - CLOUDSDK_COMPUTE_REGION=us-east4
    - CLOUDSDK_COMPUTE_ZONE=us-east4
    - CLOUDSDK_CONTAINER_CLUSTER=gf-gcloud-hml