steps:
- id: 'Build image'
  name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-f', './.devops/Dockerfile.prod', '-t', 'us-east4-docker.pkg.dev/prj-hml-excelencia/coletor/coletor-fe:$SHORT_SHA', '.' ]

- id: 'Push image'
  name: 'gcr.io/cloud-builders/docker'
  args: [ 'push', 'us-east4-docker.pkg.dev/prj-hml-excelencia/coletor/coletor-fe:$SHORT_SHA']

steps:
- id: 'Deploy image'
  name: 'us-east4-docker.pkg.dev/prj-hml-excelencia/deploy/helm:latest'
  args: ['upgrade', '--install', 'coletor-fe', './.devops/coletor-fe', '--namespace', 'coletor', '--create-namespace']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-east4'
  - 'CLOUDSDK_CONTAINER_CLUSTER=gf_gcloud'