FROM node:16-alpine as build
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH
COPY package.json package-lock.json ./

RUN npm i --silent
RUN npm i react-scripts@5.0.0 -g --silent
COPY . ./
RUN npm run build

FROM nginx:1.25.1-alpine
COPY --from=build /app/build /usr/share/nginx/html

COPY ./.devops/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]