version: '3.8'

services:
  coletor-fe:
    container_name: coletor-fe
    build:
      context: ..
      dockerfile: "./.devops/Dockerfile.dev"
    ports:
      - 3001:80
    environment:
      - REACT_APP_BASE_URL=/
      - REACT_APP_URL=https://rede-api-hml.gerandofalcoes.com/graphql