version: '3.7'

services:

  coletor-fe:
    container_name: coletor-frontend
    build:
      context: ..
      dockerfile: "Dockerfile.dev"
    ports:
      - 3001:80
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_BASE_URL=/
      - REACT_APP_URL=https://rede-api-hml.gerandofalcoes.com/graphql