FROM node:16-alpine

WORKDIR /app

ENV PATH /app/node_modules/.bin:$PATH

COPY package.json package-lock.json ./

RUN npm i --silent
RUN npm i react-scripts@5.0.0 -g --silent
RUN npm i -W caniuse-lite
COPY . ./
# RUN pm2 delete regf-hml-front

CMD npx --yes browserslist@latest --update-db;yarn start --name regf-hml-coletor-fe